### ISSUE TITLE
[BUG] Missing emissions error when setting parameter at most granular level only

### ISSUE THREAD

**Issue by SEAJang** [LDAR-Sim/LDAR_Sim#229] opened 2024-06-20 19:56 UTC
### Bug/Defect description

You get a missing emission value error when you set the emissions parameter at the most granular level only, ie. don't set the virtual world level emissions_rate_source and emissions_production_rate and instead set them for each individual component. 

### Steps to reproduce

Don't use the virtual world parameter file to set the emissions characteristics. 

### Evidence

Cannot run ldar-sim if the virtual world level doesn't have any emissions characteristics, even if they are set all at the granular level properly. 

### Expected behavior

You should be able to set the emissions values at any level only, and if you set it in the infrastructure files only, the simulator should still be able to run. 

### Version Number

v4.0.0

### Additional Context

Have yet to test if you can duplicate this problem by setting the emissions characteristics with the sites file. It is known that you cannot have it set in the component file only (propagating it down from the site/equipment files. I suspect it will still not work.

**Comment by ThomasGalesloot** [comment] 2024-07-03 22:56
Notes: Cannot reproduce the issue using emissions rate sources and emissions product rates set in the sites file. This indicates that the issue stems from parameter propagation at a lower level than the sites level. Will attempt next to reproduce with equipment.

**Comment by ThomasGalesloot** [comment] 2024-07-03 23:13
Update; Was able to produce an error setting emissions rate sources and emissions production rates at the equipment level - looking into the cause now

**Comment by ThomasGalesloot** [comment] 2024-07-04 20:09
> Update: Was able to produce an error setting emissions rate sources and emissions production rates at the equipment level

This error was resolved but was a different issue than the one reported here. Was not able to reproduce this issue in testing and have evidence to believe it was due to user error. Closing ticket.

**Closed by ThomasGalesloot** 2024-07-04 20:09 UTC
Labels: bug
