### ISSUE TITLE
[BUG] Generator files not working as intended

### ISSUE THREAD

**Issue by SEAJang** [LDAR-Sim/LDAR_Sim#220] opened 2024-06-18 21:31 UTC
### Bug/Defect description

Generator file remake is not working as intended.
When re-running a simulation with the same generator file, but different program and or method, the simulation will error out. 

### Steps to reproduce

1. Run a simulation
2. Change something about a method within the simulation
3. Re-run using the same generator files

### Evidence

Deleting the generator files and re-running the simulation will ensure that the program runs.

### Expected behavior

The generator file should be remade in this instance. 

### Version Number

v4.0.0

**Comment by ThomasGalesloot** [comment] 2024-07-04 20:50
Unable to reproduce. Closing Issue.

**Closed by ThomasGalesloot** 2024-07-04 20:50 UTC
Labels: bug
